server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://asqorrrtd2.m45t3jg8lq.tsdb.cloud.timescale.com:36605/tsdb?sslmode=require
    username: tsdbadmin
    password: cml11blngbjg4cg9
    driverClassName: org.postgresql.Driver
  http:
    converters.preferred-json-mapper: jackson
    mediaType.default : application/json
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=agrivis;AccountKey=${ACCOUNT_KEY};EndpointSuffix=core.windows.net
    container-name: agrivis

client:
  model: https://example-model-dep-workspa-ugqxl.eastus.inference.ml.azure.com
  model-token: ${TOKEN}
  disease: https://636a-34-125-197-242.ngrok-free.app
  stress: https://9aaf-34-16-181-30.ngrok-free.app
  yield: https://8ec9-34-91-168-199.ngrok-free.app
  tool: http://127.0.0.1:5000

web-odm:
  username: DinukaKariyawasam
  password: ${WEB_ODM_PASSWORD}
  url: http://localhost:8000

iot:
  url: http://iot.gsentry.cloud

scheduler:
  enabled: true